# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19dbe33dafb57400ccfde2ebec36c3deb6d9f50476dc10fc535a3696fa33abd5f7bed8f571091d2884b035afd267896e9c74b06e6b655e707d5d437b5bbae76

test:
  secret_key_base: a8290c49b699c2871a655101444027cb9472a9b6895d9641d6b3b09a3e2ac39771b9f3ea46265b1a5cb4ebd22502bd7d4250e12e579fe88f028125e51fd8db8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
